version: '2'
services:
  db:
    image: postgres
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  web:
    build: .
    entrypoint: ./wait-for-postgres.sh db
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    volumes:
      - .:/oak-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
