version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
    - '5432:5432'
  web:
    image: oakdev/oak-api
    restart: always
    ports:
      - '80:3000'
    depends_on:
      - db
    env_file:
      - web.env
