version: "3"
services:
  db:
    image: postgres
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: ./docker-entrypoint.sh
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    environment:
      - OAK_DATABASE_HOST=db
    volumes:
      - .:/oak-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
