version: '2'
services:
  db:
    image: postgres
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ./docker/startup.sh
    environment:
      - OAK_DATABASE_HOST=db
    volumes:
      - .:/oak-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
