version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    restart: always
    ports:
    - '5432:5432'
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - '5050:5050'
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    entrypoint: ./bin/docker-entrypoint
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/oak-api'
    ports:
      - '3000:3000'
    depends_on:
      - db
      - mailcatcher
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: