default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: postgres
  host: db

development:
  <<: *default
  database: oak_development
  
test:
  <<: *default
  database: oak_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>