default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oak_development
  username: postgres
  host: db

test:
  <<: *default
  database: oak_test
  username: postgres
  host: db

production:
  <<: *default
  database: oak_production
  host: <%= ENV['OAK_DATABASE_HOST'] %>
  username: <%= ENV['OAK_DATABASE_USERNAME'] %>
  password: <%= ENV['OAK_DATABASE_PASSWORD'] %>
