# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb99ad24387c931b5221bc2e8a03a5763dcb531a1c04c11244eb657c195272195a786dd75cfbee11e51a7c3ccc9b03d67dd9b824d26ea8d93c330328539b303d

test:
  secret_key_base: 3bd7243b2c506434dce8b3bffcd91a844cfcc096b4dd6670ad3b4aec31f4854685f34cfe8a9588c105ed45a7e1810cb090b48a5edeb2cc2b49d3f7f65fa6ddea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
